name: sl_v4
version: 4.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  pretty_dio_logger: ^1.3.1
  lottie: ^3.1.0
  logger: ^2.1.0
  device_info_plus: ^9.1.2
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  awesome_notifications: ^0.9.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  convex_bottom_bar: ^3.2.0
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  flutter_gen: ^5.4.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/app/gen/
  line_length: 999
  parse_metadata: false

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

  assets:
    enabled: true
    outputs:
      style: camel-case
      class_name: Assets
    exclude: []

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/lottie/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: solaiman
      fonts:
        - asset: assets/fonts/solaiman-Lipi.ttf
    - family: siyam_rupali
      fonts:
        - asset: assets/fonts/Siyam-Rupali-ANSI.ttf
