name: sl_v4
version: 4.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  lottie: ^3.0.0
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  device_info_plus: ^9.1.2
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  social_share: ^2.3.1
  timeline_tile: ^2.0.0
  uni_links: ^0.5.1
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9
  awesome_notifications: ^0.9.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  sms_autofill: ^2.3.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  molten_navigationbar_flutter: ^1.0.1
  convex_bottom_bar: ^3.2.0
  flutter_typeahead: ^5.2.0
  photo_view: ^0.14.0
  bubble: ^1.2.1
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.7.0
  youtube_player_flutter: ^8.1.2
  path_provider: ^2.1.2
  printing: ^5.11.1
  bijoy_helper: ^1.0.1
  syncfusion_flutter_pdf: ^24.2.6
  flutter_holo_date_picker: ^1.1.3
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  flutter_gen: ^5.4.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/app/gen/
  line_length: 999
  parse_metadata: false

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

  assets:
    enabled: true
    outputs:
      style: camel-case
      class_name: Assets
    exclude: []

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/lottie/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: solaiman
      fonts:
        - asset: assets/fonts/solaiman-Lipi.ttf
    - family: siyam_rupali
      fonts:
        - asset: assets/fonts/Siyam-Rupali-ANSI.ttf
