name: getx_ultimate_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.3
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  lottie: ^3.1.2
  logger: ^2.3.0
  device_info_plus: ^10.1.0
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  awesome_notifications: ^0.9.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  flutter_screenutil: ^5.9.3
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10
  internet_connection_checker: ^1.0.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_gen: ^5.4.0
  path_provider: ^2.1.3
  spider: ^4.2.2

  flutter_launcher_icons:
  change_app_package_name:
  rename_app:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf

spider:
  generate_tests: false
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: app/core/values/resources
  groups:
    - path: assets/icons
      class_name: AppIcons
      types: [.png, .svg]
    - path: assets/images
      class_name: AppImages
      types: [.png, .jpg, .jpeg, .webp]
