// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYW4Bs3RlUFh3E4Oq2KnLTLBqXlcm12EE',
    appId: '1:567425442183:web:f212c4e193db00dd34f322',
    messagingSenderId: '567425442183',
    projectId: 'dummy-app-7074',
    authDomain: 'dummy-app-7074.firebaseapp.com',
    storageBucket: 'dummy-app-7074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFA8Esuk3ncrDSNjhMz7ZMNMhhG-pkzA',
    appId: '1:567425442183:android:2311256851b5a0bf34f322',
    messagingSenderId: '567425442183',
    projectId: 'dummy-app-7074',
    storageBucket: 'dummy-app-7074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC31ydQrRgYKn8ZdcleK2Avtf4iyb1n9M',
    appId: '1:567425442183:ios:948389defa64373134f322',
    messagingSenderId: '567425442183',
    projectId: 'dummy-app-7074',
    storageBucket: 'dummy-app-7074.appspot.com',
    iosBundleId: 'com.shoplover.slV4',
  );
}
