// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:getx_ultimate_template/flavors/build_config.dart';

import '../../../../flavors/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return BuildConfig.instance.environment == Environment.PRODUCTION ? androidProd : androidDev;
      case TargetPlatform.iOS:
        return BuildConfig.instance.environment == Environment.PRODUCTION ? iosProd : iosDev;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqQHmoU8e1fmOZq5o0axrk2659oGRMNfQ',
    appId: '1:94087615646:web:159e97494642503375978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    authDomain: 'getx-ultimate-template.firebaseapp.com',
    storageBucket: 'getx-ultimate-template.appspot.com',
    measurementId: 'G-26TRZ3LXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UpLUYwGj9di2AUFSoOBsSOahzQ3M9Yo',
    appId: '1:94087615646:android:009d59453e7ac74c75978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    storageBucket: 'getx-ultimate-template.appspot.com',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyA1UpLUYwGj9di2AUFSoOBsSOahzQ3M9Yo',
    appId: '1:94087615646:android:009d59453e7ac74c75978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    storageBucket: 'getx-ultimate-template.appspot.com',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyA1UpLUYwGj9di2AUFSoOBsSOahzQ3M9Yo',
    appId: '1:94087615646:android:0ddb9eaebdb26d6175978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    storageBucket: 'getx-ultimate-template.appspot.com',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyAihjMeDR-mgU8oaULArKg1P9gDvlwmb88',
    appId: '1:94087615646:ios:dd24e7d16d69772975978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    storageBucket: 'getx-ultimate-template.appspot.com',
    iosBundleId: 'dev.solobit.getxUltimateTemplate',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyAihjMeDR-mgU8oaULArKg1P9gDvlwmb88',
    appId: '1:94087615646:ios:5710b152c5bc34c075978f',
    messagingSenderId: '94087615646',
    projectId: 'getx-ultimate-template',
    storageBucket: 'getx-ultimate-template.appspot.com',
    iosBundleId: 'dev.solobit.getxUltimateTemplate.dev',
  );
}
